// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TerminiDataAccess.TerminiContext
{
    public partial class TerminiContextModel
    {
        private TerminiContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("bb623b65-1db2-46a0-af65-359f421628b1"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var player = PlayerEntityType.Create(this);

            PlayerEntityType.CreateAnnotations(player);

            AddAnnotation("ProductVersion", "9.0.2");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
