// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TerminiDataAccess.TerminiContext
{
    public partial class TerminiContextModel
    {
        private TerminiContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("a347ec25-bdb1-4141-9e2e-83ca1e0a310e"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var player = PlayerEntityType.Create(this);
            var termin = TerminEntityType.Create(this);
            var terminPlayers = TerminPlayersEntityType.Create(this);

            TerminPlayersEntityType.CreateForeignKey1(terminPlayers, player);
            TerminPlayersEntityType.CreateForeignKey2(terminPlayers, termin);

            PlayerEntityType.CreateAnnotations(player);
            TerminEntityType.CreateAnnotations(termin);
            TerminPlayersEntityType.CreateAnnotations(terminPlayers);

            AddAnnotation("ProductVersion", "9.0.5");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
