// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using TerminiDataAccess.TerminiContext;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(TerminiContext), typeof(TerminiContextModel))]
